(base) root@ubuntu:/home/wen/LDI/Experiments/scripts/PoC/pyo# python boot_221.py 

WxPython is not found for the current python version.
Pyo will use a minimal GUI toolkit written with Tkinter (if available).
This toolkit has limited functionnalities and is no more
maintained or updated. If you want to use all of pyo's
GUI features, you should install WxPython, available here:
http://www.wxpython.org/

*** buffer overflow detected ***: python terminated
Aborted (core dumped)
(base) root@ubuntu:/home/wen/LDI/Experiments/scripts/PoC/pyo# ll /var/crash/
total 16936
drwxrwsrwt  2 root whoopsie     4096 Sep 17 15:41  ./
drwxr-xr-x 14 root root         4096 Aug  6  2020  ../
-rw-------  1 root whoopsie 17453056 Sep 17 15:41 '!usr!lib!anaconda3!bin!python3.7.4262.1631946047.6'
(base) root@ubuntu:/home/wen/LDI/Experiments/scripts/PoC/pyo# gdb python /var/crash/\!usr\!lib\!anaconda3\!bin\!python3.7.4262.1631946047.6 
GNU gdb (Ubuntu 8.1.1-0ubuntu1) 8.1.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python...done.

warning: core file may not match specified executable file.
[New LWP 4262]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `python boot_221.py'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007fb2f62e6921 in __GI_abort () at abort.c:79
#2  0x00007fb2f632f967 in __libc_message (action=action@entry=(do_abort | do_backtrace), fmt=fmt@entry=0x7fb2f645c8fb "*** %s ***: %s terminated\n")
    at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007fb2f63dab8f in __GI___fortify_fail_abort (need_backtrace=need_backtrace@entry=true, msg=msg@entry=0x7fb2f645c878 "buffer overflow detected")
    at fortify_fail.c:33
#4  0x00007fb2f63dabb1 in __GI___fortify_fail (msg=msg@entry=0x7fb2f645c878 "buffer overflow detected") at fortify_fail.c:44
#5  0x00007fb2f63d88a0 in __GI___chk_fail () at chk_fail.c:28
#6  0x00007fb2f4ad3a72 in Server_jack_init ()
   from /usr/lib/anaconda3/lib/python3.7/site-packages/pyo-1.0.3-py3.7-linux-x86_64.egg/pyo/_pyo.cpython-37m-x86_64-linux-gnu.so
#7  0x00007fb2f4ab8808 in Server_boot ()
   from /usr/lib/anaconda3/lib/python3.7/site-packages/pyo-1.0.3-py3.7-linux-x86_64.egg/pyo/_pyo.cpython-37m-x86_64-linux-gnu.so
#8  0x000055ba6002572d in _PyMethodDef_RawFastCallKeywords () at /tmp/build/80754af9/python_1598874792229/work/Objects/call.c:647
#9  0x000055ba6002c7af in _PyMethodDescr_FastCallKeywords () at /tmp/build/80754af9/python_1598874792229/work/Objects/descrobject.c:288
#10 0x000055ba60091c7c in call_function (kwnames=0x0, oparg=2, pp_stack=<synthetic pointer>) at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:4593
#11 _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:3110
#12 0x000055ba5ffd4829 in _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:3930
#13 0x000055ba600250a5 in _PyFunction_FastCallKeywords () at /tmp/build/80754af9/python_1598874792229/work/Objects/call.c:433
#14 0x000055ba6008d740 in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>)
    at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:4616
#15 _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:3110
#16 0x000055ba5ffd4829 in _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:3930
#17 0x000055ba5ffd5714 in PyEval_EvalCodeEx () at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:3959
#18 0x000055ba5ffd573c in PyEval_EvalCode (co=<optimized out>, globals=<optimized out>, locals=<optimized out>)
    at /tmp/build/80754af9/python_1598874792229/work/Python/ceval.c:524
#19 0x000055ba600ecf14 in run_mod () at /tmp/build/80754af9/python_1598874792229/work/Python/pythonrun.c:1035
#20 0x000055ba600f7331 in PyRun_FileExFlags () at /tmp/build/80754af9/python_1598874792229/work/Python/pythonrun.c:988
#21 0x000055ba600f7523 in PyRun_SimpleFileExFlags () at /tmp/build/80754af9/python_1598874792229/work/Python/pythonrun.c:429
#22 0x000055ba600f8655 in pymain_run_file (p_cf=0x7ffda5fe5040, filename=0x55ba606556b0 L"boot_221.py", fp=0x55ba6069ce70)
    at /tmp/build/80754af9/python_1598874792229/work/Modules/main.c:462
#23 pymain_run_filename (cf=0x7ffda5fe5040, pymain=0x7ffda5fe5150) at /tmp/build/80754af9/python_1598874792229/work/Modules/main.c:1652
#24 pymain_run_python (pymain=0x7ffda5fe5150) at /tmp/build/80754af9/python_1598874792229/work/Modules/main.c:2913
#25 pymain_main () at /tmp/build/80754af9/python_1598874792229/work/Modules/main.c:3460
#26 0x000055ba600f877c in _Py_UnixMain () at /tmp/build/80754af9/python_1598874792229/work/Modules/main.c:3495
#27 0x00007fb2f62c7bf7 in __libc_start_main (main=0x55ba5ffb5c90 <main>, argc=2, argv=0x7ffda5fe52a8, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7ffda5fe5298) at ../csu/libc-start.c:310
#28 0x000055ba6009cff0 in _start () at ../sysdeps/x86_64/elf/start.S:103
(gdb) 
